config/routes.rb
Rails.application.routes.draw do
  get "/reports" => 'reports#index', as: :reports
  get "/customers" => 'customers#index', as: :customers
  get "/photos" => 'photos#index', as: :photos
  get "/sellers" => 'sellers#index', as: :sellers
  get "/dashboard" => 'dashboard#index', as: :dashboard
  resources :properties
  devise_for :accounts
  root to: 'public#main'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a style="text-decoration: none" class="dashboard navbar-brand col-sm-3 col-md-2 mr-0" href="/">Upstate Properties</a>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
        <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
        </li>
    </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-weight: bold" href="/">Upstate Properties</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if account_signed_in? %>
          <%= link_to "Dashboard", dashboard_path, class: "nav-link"%>
          <% end %>
        </li>
      </ul>
      <form class="d-flex">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <% if account_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_account_session_path,  method: :delete, class: "nav-link" %>
        <% else %>
        <li class="nav-item">
          <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav style="background-color: rgb(200,200,200)" class="col-md-2">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to dashboard_path, class: "sidebar nav-link", style: "color: black" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Dashboard
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to properties_path, class: "nav-link", style: "color: black" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                  Properties
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to customers_path, class: "sidebar nav-link", style: "color: black" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Customers
                 <% end %>
              </li>
              <li class="nav-item">
                  <%= link_to sellers_path, class: "nav-link", style: "color: black" do %>                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Sellers
                 <% end %>
              </li>
              <li class="nav-item">
                <%= link_to reports_path, class: "sidebar nav-link", style: "color: black" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Reports
                 <% end %>
              </li>
              <li class="nav-item">
                <%= link_to photos_path, class: "sidebar nav-link", style: "color: black" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Photos
                 <% end %>
              </li>
            </ul>
            <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        </nav>